config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :links do
      resources :comments
      member do
        patch :share, :unshare
        put "like", to: "links#upvote"
        put "dislike", to: "links#downvote"
      end
    end
  end

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments

  self.per_page = 10

  validates :title, presence: true
  validates :url, presence: true
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :find_user
  before_action :find_link, only: [:upvote, :downvote]

  def index
    if @user != current_user
      # @links = []
      # all_links = @user.links.all

      # all_links.each do |link|
      #   if link.sharing == true
      #     @links << link
      #   end
      # end
      @links = @user.links.where(sharing: true).order("created_at DESC").paginate(page: params[:page])
    else
      #@links = @user.links.all
      @links = @user.links.order("created_at DESC").paginate(page: params[:page])
    end
  end

  def show
    @link = @user.links.find(params[:id])
    if @user != current_user && @link.sharing == false
      redirect_to login_path
    else
      @comments = []
      @link.comments.all.each do |comment|
        # debugger
        user = User.find(comment.user_id)
        @comments << [user, comment.content]
      end
    end
  end

  def new
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.new
    end
  end

  def create
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.create(link_params)

      respond_to do |format|
        if @link.save
          flash[:success] = "Create new link successfully!"
          format.html { redirect_to user_links_path(@user) }
        else
          # flash[:error] = "Some error!"
          format.html { render 'new' }
        end
      end
    end
  end

  def edit
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.find(params[:id])
    end
  end

  def update
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.find(params[:id])
      respond_to do |format|
        if @link.update_attributes(link_params)
          flash[:success] = "Update successfully!"
          format.html { redirect_to user_links_path(@user) }
        else
          flash[:error] = "Some error here!"
          format.html { render 'edit' }
        end
      end
    end
  end

  def destroy
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.find(params[:id])
      @link.destroy
      redirect_to user_links_path
    end
  end

  def share
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.find(params[:id])
      @link.update_attribute(:sharing, true)
      # redirect_to user_links_path, notice: "Link had been shared!"
      flash[:success] = "Link had been shared"
      redirect_to user_links_path
    end
  end

  def unshare
    if @user != current_user
      redirect_to root_url
    else
      @link = @user.links.find(params[:id])
      @link.update_attribute(:sharing, false)
      # redirect_to user_links_path, notice: "Unshared the link now!"
      flash[:error] = "Unshared the link now"
      redirect_to user_links_path
    end
  end

  def upvote
    @link.upvote_by current_user
    @link.update_attribute(:like_count, @link.get_upvotes.size)
    @link.update_attribute(:votes, @link.votes_for.size)
    redirect_to :back
  end

  def downvote
    @link.downvote_by current_user
    @link.update_attribute(:like_count, @link.get_upvotes.size)
    @link.update_attribute(:votes, @link.votes_for.size)
    redirect_to :back
  end

  private

  def link_params
    params.require(:link).permit(:title, :description, :url)
  end

  def find_user
    @user = User.find(params[:user_id])
  end

  def find_link
    find_user
    @link = @user.links.find(params[:id])
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/edit.html.erb
<div class="page_title">
  Edit The Link
</div>

<div class="page_content">

  <%= form_for([@user, @link]) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_area :description, placeholder: "Add some description about the site" %>
    <%= f.label :url %>
    <%= f.text_field :url %>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= f.submit 'Update', class: "new-btn"%>
      </div>
    </div>
  <% end %>
</div>

app/views/links/index.html.erb
<% provide(:title, @user.name)%>

<div class="page_title">
  My Links
</div>


<div class="page_content">
  <div class="my_lists">
    <% if @user == current_user %>
      <% @links.each do |link| %>
        <div class="my_item">
          <div class="link_title">
            <%= link_to link.title, "http://#{link.url}" %>
          </div>
          <div class="link_action">
            <% if link.sharing == true %>
              <%= link_to unshare_user_link_path(@user, link), method: :patch do %>
                <span class="glyphicon glyphicon-ban-circle"></span>
              <% end %>
            <% else %>
              <%= link_to share_user_link_path(@user, link), method: :patch do %>
                <span class="glyphicon glyphicon-share"></span>
              <% end %>
            <% end %>
            <%= link_to user_link_path(@user, link) do %>
              <span class="glyphicon glyphicon-expand"></span>
            <% end %>
            <%= link_to edit_user_link_path(@user, link) do %>
              <span class="glyphicon glyphicon-edit"></span>
            <% end %>
            <%= link_to user_link_path(@user, link), method: :delete, data: { confirm: "Are you sure" } do %>
              <span class="glyphicon glyphicon-trash"></span>
          </div>
            <% end %>
        </div>

      <% end %>

      <div class="bottom_line">
      </div>

      <p><%#= link_to 'New Link', new_user_link_path(@user) %></p>
    <% else %>

      <% @links.each do |link| %>
        <div class="my_item">
          <div class="link_title">
            <%= link_to link.title, "http://#{link.url}" %>
          </div>

          <div class="link_action">
            <%= link_to user_link_path(@user, link) do %>
              <span class="glyphicon glyphicon-expand"></span>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="bottom_line">
      </div>

    <% end %>
  </div>

  <div class="page_count">
    <%= will_paginate @links %>
  </div>
</div>

app/views/links/new.html.erb
<div class="page_title">
  New Link
</div>

<div class = "page_content">
  <div class="form">
    <%= form_for([@user, @user.links.build]) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :title %>
      <%= f.text_field :title, placeholder: "Page title" %>
      <%= f.label :description %>
      <%= f.text_area :description, placeholder: "Add some description about the site" %>
      <%= f.label :url %>
      <%= f.text_field :url, placeholder: "\" http(s):// \" is not need !"%>
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <%= f.submit "Create", class: "new-btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/links/show.html.erb
<div class="page_title">
  <%= link_to @link.title, "http://#{@link.url}" %>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p>
      <%= @link.description %>
    </p>

    <% if logged_in? %>
      <p>
        <%= link_to  like_user_link_path(@user, @link), method: :put do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <%= @link.get_upvotes.size %>
        <% end %>
        <%= link_to  dislike_user_link_path(@user, @link), method: :put do %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <%= @link.get_downvotes.size %>
        <% end %>
      </p>

      <div class="commnets_form">
        <%= form_for([@user, @link, @link.comments.build]) do |f| %>
          <%= f.label :comment %>
          <%= f.text_area :content %>
          <div class="row">
            <div class="col-md-3 col-md-offset-9">
              <%= f.submit "submit", class: "new-btn" %>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>
        <span class="unvotable">
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <%= @link.get_upvotes.size %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <%= @link.get_downvotes.size %>
        </span>
      </p>
      <p>
        Please <%= link_to 'log in', login_path %> to comment, don't have an account? <%= link_to 'Sign up', signup_path %>!
      </p>
    <% end %>



    <p>Comments: </p>
    <% @comments.each do |comment| %>
      <p><%= link_to comment[0].name.capitalize, user_path(comment[0]) %>: <%= comment[1] %></p>
    <% end %>
  </div>
</div>