config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :links do
      resources :comments
      member do
        patch :share, :unshare
        put "like", to: "links#upvote"
        put "dislike", to: "links#downvote"
      end
    end
  end

  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
  <p>Twitter: <a href="#">@lafwind</a></p>
  <p>Copyright 2014</p>
</footer>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <div class="header_photo">
    <%= gravatar_for(current_user) %>
  </div>
  <div class="user_detail">
    <li class="links <%= 'select' if params[:controller] == 'links' && params[:action] == 'index'%>">
      <%= link_to "Links", user_links_path(current_user.id) %>
    </li>

    <li class="profile <%= 'select' if params[:controller] == 'users' && params[:action] == 'show'%>">
      <%= link_to "Profile", current_user %>
    </li>

    <li class="setting <%= 'select' if params[:controller] == 'users' && params[:action] == 'edit'%>">
      <%= link_to "Settings", edit_user_path(current_user) %>
    </li>

    <li class="nothing">.</li>

    <%= link_to  new_user_link_path(current_user) do %>
      <li class="new_link">New Link</li>
    <% end %>
  </div>
  <li class=<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'home' %>><%= link_to "Discover", root_path %></li>
  <li class=<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'about' %>><%= link_to "About", about_path %></li>
  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
<% else %>
  <div class="log_out">
    <li class="brand"><%= link_to "LINK", root_path %></li>
    <li class=<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'home' %>><%= link_to "Discover", root_path %></li>
    <li class=<%= 'active' if params[:controller] == 'static_pages' && params[:action] == 'about' %>><%= link_to "About", about_path %></li>
    <li class=<%= 'active' if params[:controller] == 'users' && params[:action] == 'new' %>><%= link_to "Sign up", signup_path %></li>
    <li class=<%= 'active' if params[:controller] == 'sessions' && params[:action] == 'new' %>><%= link_to "Log in", login_path %></li>
  </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

  <div class="side_bar">
    <div class="top">
      <%= render 'layouts/header' %>
    </div>
    <div class="bottom">
      <%= render 'layouts/footer' %>
    </div>
  </div>

  <div class="main">

    <% flash.each do |message_type, message| %>
      <div class="notice_wrapper">
        <div class="notice notice-<%= message_type %>"><%= message %></div>
      </div>
    <% end %>

    <%= yield %>
    <%#= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>